parameters:
#    afpa_artiste.example.class: Afpa\ArtisteBundle\Example

services:
#    afpa_artiste.example:
#        class: %afpa_artiste.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    afpa_artiste.twig.popuplus_extension:
        class: Afpa\ArtisteBundle\Twig\Extension\PopuplusExtension
        tags: 
        - { name: twig.extension }