parameters:
#    calculette.example.class: Afpa\CalculetteBundle\Example

services:
#    calculette.example:
#        class: %calculette.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
